name: SlimePlugin
main: org.masterpi.mc.slimeplugin.SlimePlugin
version: ${pom.version}
description: Plugin to help users find slime chunks
author: MasterPi

commands:
   slime:
      description: Tells you if you are in a slime chunk.
      usage: /<command>
